"""empty message

Revision ID: 7647d882cbd0
Revises: 7fb82c18a7d0
Create Date: 2024-12-30 21:22:59.132980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7647d882cbd0'
down_revision = '7fb82c18a7d0'
branch_labels = None
depends_on = None


def upgrade():
    # Add column with a server default to prevent null errors
    op.add_column('user', sa.Column('role', sa.String(length=50), nullable=False, server_default='user'))

    # Optionally, remove the server default after applying to prevent unintended use
    op.alter_column('user', 'role', server_default=None)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
